### PR TITLE
upgrade: ttest@2.x

### PR DESCRIPTION
**Pull request by DonutEspresso**
ttest@2.x picks up [cephes](https://www.npmjs.com/package/cephes) in favor of [mathfn](https://www.npmjs.com/package/mathfn), which is no longer maintained. The version of mathfn picked up in the current ttest@1.x tree is missing functions outright. With the upgrade to ttest@2.x all tests seem to pass (and works as expected in restify repo).

### CODE REVIEW

**Comment by mcollina** [comment]
Can you please update the `.travis.yml` file? This would also be updated to new format of aautocannon @3.

**Comment by DonutEspresso** [comment]
Done! This seems to fail on Node6 unfortunately, as `cephes` uses WebAssembly under the hood:

```
/home/travis/build/mcollina/autocannon-compare/node_modules/cephes/cephes-wrapper.js:14
    this._wasmMemory = new WebAssembly.Memory({
                           ^
ReferenceError: WebAssembly is not defined
    at new CephesWrapper (/home/travis/build/mcollina/autocannon-compare/node_modules/cephes/cephes-wrapper.js:14:28)
    at Object.<anonymous> (/home/travis/build/mcollina/autocannon-compare/node_modules/cephes/cephes.js:5:18)
```

How do you feel about dropping support for Node6? I'm not sure what the alternative is, I haven't tried `ttest@1.x` but could investigate more.

**Comment by mcollina** [comment]
Go for it, let's drop Node 6.

**Comment by DonutEspresso** [comment]
I think all looks good here - let me know if there's anything else needed. Thanks!

**Comment by mcollina** [comment]
@DonutEspresso would you like to send  a PR for the new format of autocannon as well?

**Comment by DonutEspresso** [comment]
We are still on 2.x, but if I get a chance I'll take a look. Thanks for the release!

**Pull request merged**
